## Importing Numpy

In [1]:
import numpy as np

## Creating Arrays

### Creating Arrays with Zeros, Ones, or Constants

In [2]:
zeroes_array = np.zeros(5)
ones_array = np.ones(5)
constant_array = np.full(10, 3)

constant_array

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

### Converting Lists to Arrays

In [3]:
my_list = [1,2,3,4]
np_array = np.array(my_list)
np_array

array([1, 2, 3, 4])

### Generating Ranges of Numbers


In [4]:
range_array = np.arange(10) # arrary from 0 to 9
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Arrays with Linear Spacing


In [5]:
linespace_array = np.linspace(1, 10, 5)
linespace_array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### Multi-dimensional Arrays


In [6]:
zeroes_matrix = np.zeros((2, 2))
ones_matrix = np.ones((2, 2))
const_matrix = np.full((2, 2), 2)
const_matrix


array([[2, 2],
       [2, 2]])

### Indexing and Slicing Arrays


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
first_row = arr[0]
first_col = arr[:, 0]
first_col

array([1, 4])

### Generating Random Arrays


In [8]:
np.random.seed(2)

random_array = np.random.rand(5, 2)
random_array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [9]:
normal_distribution = np.random.randn(5, 2)
random_integers = np.random.randint(low=0, high=100, size=(5, 2))
random_integers

array([[83, 31],
       [66, 80],
       [52, 76],
       [50,  4],
       [90, 63]])

## Array Operations


### Element-wise Operations

In [10]:
arr + 1


array([[2, 3, 4],
       [5, 6, 7]])

### Element-wise Operations with Two Arrays


In [11]:
arr1 = np.ones(4)
arr2 = np.full(4, 3)
result = arr1 + arr2
result

array([4., 4., 4., 4.])

### Comparison Operations

In [12]:
arr = np.array([1, 2, 3, 4])
greater_than_2 = arr > 2
greater_than_2

array([False, False,  True,  True])

### Selecting Elements Based on Conditions

In [13]:
arr_filtered = arr[arr > 2]
arr_filtered

array([3, 4])

### Summary Operations


In [14]:
min_value = arr.min()    # Minimum value
max_value = arr.max()    # Maximum value
sum_value = arr.sum()    # Sum of all elements
mean_value = arr.mean()  # Mean (average) value
std_deviation = arr.std()  # Standard deviation