## Linear Algebra Refresher

### Vector operations


In [2]:
import numpy as np

u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

u + v

u - v

2 * u

array([ 4, 14, 10, 12])

### Multiplication

#### Vector-vector multiplication


In [ ]:
def vector_vector_multiplication(u, v):
  assert u.shape[0] == v.shape[0]

  n = u.shape[0]

  result = 0.0

  for i in range(n):
    result += u[i] * v[i]

  return result

vector_vector_multiplication(np.array([1,2,3]), np.array([1,2,3]))

(2, 3)

#### Matrix-vector multiplication


In [22]:
def matrix_vector_multiplication(U, v):
  assert U.shape[1] == v.shape[0]

  n = U.shape[0]

  result = np.zeros(n)

  for i in range(n):
    ans = vector_vector_multiplication(U[i], v)
    result[i] = ans
  return ans

matrix_vector_multiplication(np.array([[1,2,3], [4,5,6]]), np.array([1,2,3]))

np.float64(32.0)

#### Matrix-matrix multiplication

In [23]:
def matrix_matrix_multiplication(U, V):
  assert U.shape[1] == V.shape[0]

  num_rows = U.shape[0]
  num_cols = V.shape[1]

  result = np.zeros((num_rows, num_cols))

  for i in range(num_cols):
    vi = V[:, i]
    Uvi = matrix_vector_multiplication(U, vi)
    result[:, i] = Uvi

  return result

matrix_matrix_multiplication(np.array([[1,2], [4,5]]), np.array([[1,2,3], [4,5,6]]))

array([[24., 33., 42.],
       [24., 33., 42.]])

### Identity matrix


In [ ]:
I = np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Inverse

In [ ]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])

inv = np.linalg.inv(V)

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])